08-01-16: Update to v0.9.8-(080116)

diff --git a/back2ntfs b/back2ntfs
--- a/back2ntfs
+++ b/back2ntfs
@@ -1,83 +1,74 @@
 #!/bin/bash
 
 #
-# Back2NTFS 
+# Back2NTFS
 # by Andy Forceno <andy@aurorabox.tech>
 #
 # Tar /home/user and /etc on many remote hosts
 # Copy to an NTFS NAS device & create and verify SHA1 checksums
 # To be run bi-weekly via cron
 #
-
-# Location of local disk copy of repo
-BASEDIR="$HOME/scripts/bin"
-
-# Location to log to on each host specified in hosts_check
-CONFIG_PATH="$HOME/.config/shuttle-utils"
-
-# Path to backup dir
-BACKUP_PATH="/media/andy/external/Backups"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+  source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+  echo "SHuttle-utils: Error: No config file found!"
+  exit 1
+fi
 
 # TODO: Add TARGET_DIRS array eventually
 # TARGET_DIRS=("/home/andy" "/etc")
 
 # Check if machines are available before updating
-source "$BASEDIR"/hosts_check
+source "$bin_path"/hosts_check
 
-# Remove Hostname from hosts array, it has no hard disks
-# HOSTS=($(echo "${HOSTS[@]}" | sed -e "s/Hostname//g"))
-
-echo -e "$0: ***** Begin back2ntfs.sh *****\n"
-echo -e "$0: See "$CONFIG_PATH/back2ntfs-$(date +%m%d%y).log" on each host for individual backup logs"
+echo -e "Back2NTFS: ***** Begin back2ntfs.sh *****\n"
+echo -e "Back2NTFS: See "$conf_path/back2ntfs-$(date +%m%d%y).log" on each host for individual backup logs"
 
 for i in "${HOSTS[@]}"; do
   echo "Connecting to: $i"
   # Pass locally-declared vars to remote host
-  ssh "$i" LC_0="$0" LC_i="$i" LC_basedir="$BASEDIR" LC_config_path="$CONFIG_PATH" LC_backup_path="$BACKUP_PATH" bash -x << 'EOF' 
+  ssh "$i" LC_i="$i" LC_bin_path="$bin_path" LC_conf_path="$conf_path" LC_backup_path="$backup_path" LC_shuttle_path="$shuttle_path" bash -x << 'EOF' 
 
-  # If $CONFIG_PATH doesn't exist, create it
-  if [ ! -d "$LC_config_path" ]; then
-    mkdir "$LC_config_path"
+  # If $conf_path doesn't exist, create it
+  if [ ! -d "$LC_conf_path" ]; then
+    mkdir "$LC_conf_path"
   fi
 # Create the log file
-  touch "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
+  touch "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log
 
   # Backup /home/andy
-  echo -e "$LC_0: $LC_i: Creating tar file of /home/andy in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
-  sudo touch "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
+  echo -e "Back2NTFS: $LC_i: Creating tar file of /home/andy in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log
+  sudo touch "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log
   # Exclude caches, and most folders that begin with a dot
-  # INFO: You should edit the contents of .excludes in your local copy of shuttle-utils to match the correct paths on your device
-  tar -X "$LC_basedir"/.excludes --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar /home/andy >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log && wait
-  # SHA1 checksum creation is now done in the loop below
-  # sha1sum "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar > "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar.sha1 >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log 
+  # INFO: You should edit $conf_path/.excludes to match the correct paths on your device
+  tar -X "$LC_conf_path"/.excludes --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar /home/andy >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log && wait
 
   # Backup /etc
-  echo -e "$LC_0: $LC_i: Creating tar file of /etc in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
+  echo -e "Back2NTFS: $LC_i: Creating tar file of /etc in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log
 # TODO: Log file is not created on some hosts (permissions issue?)
-  sudo touch "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
-  sudo tar --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar /etc >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log && wait
- # sha1sum "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar > "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar.sha1 >> "$LC_config_path"/back2ntfs-$(date +%m%d%y).log
+  sudo touch "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log
+  sudo tar --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar /etc >> "$LC_conf_path"/back2ntfs-$(date +%m%d%y).log && wait
 EOF
 
   # Location of backups on host executing back2ntfs 
   # In my case this is different than the location on remote hosts
   cd /media/external/Backups/"$i"/
   # Find and delete .tar and .sha1 files older than 2 months (should preserve 1 old backup)
-  echo "$LC_0: Deleting old backups..."
+  echo "Back2NTFS: Deleting old backups..."
   find . -type f \( -iname \*.tar -o -iname \*.sha1 \) -mtime +60 -exec rm -i -f {} \+ 
 
   ## Create and verify SHA1 checksums for new backups 
   for j in $(find . -name '*.tar'); do
-    echo "$LC_0: Creating SHA1 checksum of "$BACKUP_PATH"/"$i"/$(echo "$j" | sed -e 's#\.\/##g')..."
+    echo "Back2NTFS: Creating SHA1 checksum of "$backup_path"/"$i"/$(echo "$j" | sed -e 's#\.\/##g')..."
     sha1sum "$j" > "$j.sha1" && wait
-    echo "$LC_0: Verifying SHA1 checksum of "$BACKUP_PATH"/"$i"/$(echo "$j" | sed -e 's#\.\/##g')..."
+    echo "Back2NTFS: Verifying SHA1 checksum of "$backup_path"/"$i"/$(echo "$j" | sed -e 's#\.\/##g')..."
     sha1sum -c "$j.sha1" && wait $!
     
     if [[ "$?" = "1" ]]; then
-      /usr/bin/shuttle -p -n all "$i: Bad checksum!" "$j failed checksum verification at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
+      "$shuttle_path"/shuttle -p -n all "$i: Bad checksum!" "$j failed checksum verification at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
     fi
   done
 done
 
-echo -e "$0: ***** End back2ntfs.sh ***** Goodbye!\n"
+echo -e "Back2NTFS: ***** End back2ntfs.sh ***** Goodbye!\n"
 
diff --git a/checklogs b/checklogs
--- a/checklogs
+++ b/checklogs
@@ -1,34 +1,34 @@
 #! /bin/bash
 
 #
-# Checklogs - Check for very large log files 
+# Checklogs - Check for very large log files
 # 	by Andy Forceno <andy@aurorabox.tech>
 # 
 # Check for very large log files and alert the system administrator
 
-# Device to send push notifications to
-device="all"
-
-# Location of local disk copy of repo
-BASEDIR="$HOME/scripts/bin"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if machines are available before updating
-source "$BASEDIR"/hosts_check
+source "$bin_path"/hosts_check
 
 for i in "${HOSTS[@]}"; do
-echo "$0: Checking log files on host: $i"
+echo "checklogs: Checking log files on host: $i"
 # Pass $i and $device to remote host
 # Then, execute log size checking on remote host
 # Remote host must have SHuttle set up otherwise pushes won't be sent
-	ssh "$i" LC_0="$0" LC_i="$i" LC_device="$i" bash << 'EOF' 
+	ssh "$i" LC_i="$i" LC_device="$i" LC_shuttle_path="$shuttle_path" LC_mailto="$mailto" bash << 'EOF' 
 # Address to send mail notifications to
-mailto="root@$aurorabox"
 logsizes=$(ls -alh /var/log | awk '{ print $5 "   " $9 }' | grep 'G')
 
 if [[ -n "$logsizes" ]]; then
-	echo "$LC_0: Large log file(s) detected!" 
-	echo -e "$logsizes" | mail -s "checklogs: Large log files detected!" "$mailto"
-		/usr/bin/shuttle -p -n "$LC_device" "$LC_i: Large log files detected!" "$logsizes"
+	echo "checklogs: Large log file(s) detected!" 
+	echo -e "$logsizes" | mail -s "checklogs: Large log files detected!" "$LC_mailto"
+		"$shuttle_path"/shuttle -p -n "$LC_device" "$LC_i: Large log files detected!" "$logsizes"
 fi
 EOF
 done
diff --git a/hostname-isup b/hostname-isup
--- a/hostname-isup
+++ b/hostname-isup
@@ -7,11 +7,16 @@
 # This script could easily be expanded to include multiple hosts
 # You can borrow code from the hosts_check and spaced or smartmon scripts  :-)
 
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
+
+# TODO: Move user-defined vars to shuttle-utils.conf
 # Host IP address and name
 host_addr="192.168.1.2"
-
-# Device to send push to
-device="phone"
 
 # How often to ping host
 sleep_time="2m"
diff --git a/ipnotif b/ipnotif
--- a/ipnotif
+++ b/ipnotif
@@ -10,23 +10,28 @@
 
 # This script is brought to you by the music of Natasha Kmeto: https://soundcloud.com/natashakmeto
 
-# Location of local
-CONFIGDIR="$HOME/.config/shuttle-utils"
-
-# The device to push notifications to
-device="all"
-
-# Last known IP
-last_ip=$(tac $CONFIGDIR/.iphist | grep -m 1 '.' | awk '{print $4}')
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # API call to obtain IP address
 # See: https://www.ipify.org/
 new_ip=$(curl -s 'https://api.ipify.org?format=text')
 
-if [[ "$last_ip" != "$new_ip" ]]; then
-	/usr/bin/shuttle -p -n "$device" "$HOSTNAME: External IP address change" "Current IP: $new_ip"
+# Last known IP
+if [ -e "$conf_path/.iphistory" ]; then
+	last_ip=$(tac "$conf_path"/.iphistory | grep -m 1 '.' | awk '{print $4}')
+	if [[ "$last_ip" != "$new_ip" ]]; then
+		$shuttle_path/shuttle -p -n "$device" "$HOSTNAME: External IP address change" "Current IP: $new_ip"
+	fi
 # Write date & address to file for IP address history
-	echo "$(date "+%D %H:%M") - $new_ip" >> "$CONFIGDIR"/.iphist
+else 
+	touch "$conf_path/.iphistory" 
+fi	
+echo "$(date "+%D %H:%M") - $new_ip" >> $conf_path/.iphistory
 fi
 
 
diff --git a/reboot_notif b/reboot_notif
--- a/reboot_notif
+++ b/reboot_notif
@@ -5,14 +5,18 @@
 #
 # Sends a push notification to specified device if a reboot is needed 
 
-# Device to send push notification to
-device="phone"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Last reboot date/time
 last_reboot=$(uptime -s)
 
 if [[ -f /var/run/reboot-required ]]; then
 # Echo for logging purposes
-	echo "$0: "$HOSTNAME" requires a reboot. Last reboot was on "$last_reboot""
-	/usr/bin/shuttle -p -n "$device" "$(echo "$HOSTNAME"): reboot required" "Last reboot was on $(echo "$last_reboot")"
+	echo "$reboot_notif: "$HOSTNAME" requires a reboot. Last reboot was on "$last_reboot""
+	"$shuttle_path"/shuttle -p -n "$device" "$(echo "$HOSTNAME"): reboot required" "Last reboot was on $(echo "$last_reboot")"
 fi
diff --git a/smartmon b/smartmon
--- a/smartmon
+++ b/smartmon
@@ -10,34 +10,56 @@
 # And run the long test weekly (see smartmon_long)
 # You will need passwordless-sudo on the remote devices to automate this script
 
-# Device to send push notifications to
-device="phone"
-
-# Drive to scan
-# Currently only supports a single drive
-drive="/dev/sda"
-
-# User to send reports to 
-mailto="root@aurorabox"
-
-# Location of local disk copy of repo
-BASEDIR="$HOME/scripts/bin"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if hosts are available before running remote SMART tests
-source "$BASEDIR"/hosts_check
-
-# Remove Host from hosts array, it has no hard disks
-# HOSTS=($(echo "${HOSTS[@]}" | sed -e "s/Hostname//g"))
+source "$bin_path"/hosts_check
 
 # Iterate through hosts list
-for j in "${HOSTS[@]}"; do
-echo -e "$0: SMART Test for host: $j"
-	smart_test=$(ssh "$j" "sudo smartctl -a $drive")
-	smart_result=$(echo "$smart_test" | head -n30 | grep "overall-health" | awk -F': ' '{ print $2 }')
-echo -e "$0: $smart_result"
+for i in "${HOSTS[@]}"; do
+echo -e "smartmon: SMART Test for host: $i"
+ssh "$i" LC_i="$i" LC_percent="$percent" LC_mailto="$mailto" LC_conf_path="$conf_path" LC_shuttle_path="$shuttle_path" LC_DRIVES="${DRIVES[@]}" bash << 'EOF' 
+	for j in ${LC_DRIVES[@]}; do
+		smart_test=$(sudo smartctl -a "$j" 2>/dev/null)
+		smart_result=$(echo "$smart_test" | head -n30 | grep "overall-health" | awk -F': ' '{ print $2 }' 2>/dev/null)
+	done
+#echo -e "smartmon: $smart_result"
 # Only notify if test fails so we don't swamp the poor sys admin
 	if [[ -n "$smart_result" && "$smart_result" != "PASSED" ]]; then
 		# echo "$smart_test" | mail -s "$j: SMART Diagnostics for $drive" "$mailto"
-		/usr/bin/shuttle -p -n "$device" "$host: SMART Diagnostic info" "$drive $smart_result at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
+		"$shuttle_path"/shuttle -p -n "$device" "$LC_i: SMART Diagnostic info" "$drive $smart_result at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
 	fi
+
+# Read in saved SMART attribute values
+if [[ -e $LC_conf_path/.smart-attribs ]]; then
+	prev_realloc=$(awk -F, '{ print $1 }' $LC_conf_path/.smart-attribs)
+	prev_pending=$(awk -F, '{ print $2 }' $LC_conf_path/.smart-attribs)
+	prev_offline=$(awk -F, '{ print $2 }' $LC_conf_path/.smart-attribs)
+fi
+
+# Bad sectors that were moved
+realloc=$(echo -e "$smart_test" | awk '/Reallocated_Sector_Ct/ { print $10 }')
+# Bad sectors not yet corrected
+pending=$(echo -e "$smart_test" | awk '/Current_Pending_Sector/ { print $10 }')
+# Uncorrectable sector count
+offline=$(echo -e "$smart_test" | awk '/Offline_Uncorrectable/ { print $10 }')
+
+# Delta values
+realloc_delta=$((realloc-prev_realloc))	
+pending_delta=$((pending-prev_pending))
+offline_delta=$((offline-prev_offline))
+
+if [[ "$realloc_delta" > 0 || "$pending_delta" > 0 || "$offline_delta" > 0 ]]; then
+	"$shuttle_path"/shuttle -p -n all "$HOSTNAME: SMART values have changed!" "Changes: Reallocated +$realloc_delta, Pending +$pending_delta, Offline +$offline_delta"
+fi
+
+touch $LC_conf_path/.smart-attribs
+echo "$realloc,$pending,$offline" > "$LC_conf_path"/.smart-attribs
+EOF
 done
+
diff --git a/smartmon_long b/smartmon_long
--- a/smartmon_long
+++ b/smartmon_long
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# smartmon_long - Long S.M.A.R.T. Test Results Push Notifier
+# smartmon_long - Long S.M.A.R.T. Test Results Push Notifier 
 # 	by Andy Forceno <andy@aurorabox.tech>
 #
 # Runs the long S.M.A.R.T. test for disks on remote hosts and pushes & mails results
@@ -10,33 +10,27 @@
 
 # TODO: Full SMART test results aren't being pushed. API seems to interpret something in the smartctl output incorrectly
 
-# Device to send push notifications to
-device="chrome"
-
-# Drive to scan on remote host
-drive="/dev/sda"
-
-# Location of local disk copy of repo
-BASEDIR="$HOME/scripts/bin"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if hosts are available before running remote SMART tests
-source "$BASEDIR"/hosts_check
+source "$bin_path"/hosts_check
 
-# Remove host from hosts array, it has no hard disks
-# HOSTS=($(echo "${HOSTS[@]}" | sed -e "s/Hostname//g"))
-# user@host to send mail to (enabled by default)
-mailto="root@aurorabox"
+# TODO: Add for j in DRIVES array loop 
 # Iterate through hosts list
 for i in "${HOSTS[@]}"; do
 	echo "Smartmon_long: Connecting to: $i"
 	# Pass locally-declared vars to remote host
-	ssh "$i" LC_0="$0" LC_i="$i" LC_drive="$drive" LC_device="$device" LC_mailto="$mailto" bash << 'EOF' 
-	echo -e "$LC_0: Begin SMART long test for host: $LC_i"
-   	sudo smartctl -t long "$LC_drive" && wait $!
-    long_results=$(sudo smartctl -l selftest "$LC_drive")
-  #	echo -e "$LC_0: self-test results for $LC_i: $long_results"
-	# TODO: Mailing of test results is enabled by default, until I verify full test results are being pushed
-    echo -e "$(date +%R) on $(date +%m-%d-%y):\n $long_results" | mail -s "$LC_i: SMART long test for $LC_drive" "$LC_mailto"
-    /usr/bin/shuttle -p -n "$LC_device" "$LC_i: SMART Long Test" "$LC_drive: $long_results at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
+	ssh "$i" LC_i="$i" LC_drive="$drive" LC_device="$device" LC_mailto="$mailto" LC_shuttle_path="$shuttle_path" bash << 'EOF' 
+	echo -e "smartmon_long: Begin SMART long test for host: $LC_i"
+   	sudo smartctl -t long "$LC_drive" 2>/dev/null && wait $!
+    long_results=$(sudo smartctl -l selftest "$LC_drive" 2>/dev/null)
+  # echo -e "smartmon_long: self-test results for $LC_i: $long_results"
+  # echo -e "$(date +%R) on $(date +%m-%d-%y):\n $long_results" | mail -s "$LC_i: SMART long test for $LC_drive" "$LC_mailto"
+    "$LC_shuttle_path"/shuttle -p -n "$LC_device" "$LC_i: SMART Long Test" "$LC_DRIVES: $long_results at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
 EOF
 done
diff --git a/spaced b/spaced
--- a/spaced
+++ b/spaced
@@ -4,22 +4,22 @@
 # 	By Andy Forceno <andy@aurorabox.tech>
 #
 
-# Location of local disk copy of repo
-BASEDIR="$HOME/scripts/bin"
-
-MAILTO="root@aurorabox"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if hosts are available before checking disc space
-source "$BASEDIR"/hosts_check
+source "$bin_path"/hosts_check
 
-# Percentage threshold at which to warn user of low disk space
-percent="98"
 # Everything after the ssh command will be executed on each remote host
 # Mail will be sent to root at each remote host
 for i in "${HOSTS[@]}"; do
 	echo "Spaced: Checking disk space on $i..."
 # Pass $i to remote host
-	ssh "$i" LC_i="$i" LC_percent="$percent" LC_mailto="$MAILTO" bash << 'EOF' 
+	ssh "$i" LC_i="$i" LC_percent="$percent" LC_mailto="$mailto" LC_shuttle_path="$shuttle_path" bash << 'EOF' 
 # List of all block devices
 	df_output=$(df -lh | grep "/dev/sd.*")
 # Devices
@@ -35,9 +35,9 @@ for i in "${HOSTS[@]}"; do
 			line_num=$(echo -e "$df_output" | grep -n "$j" | cut -f1 -d:)
 		# df line with drive info
 			df_line=$(echo -e "$df_output" | grep -n "$j" | cut -d: -f2-)
-			sudo echo "Spaced: $LC_i: $(echo -e "$mounts" | sed -n $line_num'p') partition has less than $percent% free space!" >> /var/log/cron.log
-			# echo -e "$(df -lh | head -n1)\n$df_line" | mail -s "space.d: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$LC_mailto"
-			/usr/bin/shuttle -p -n all "$LC_i: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$(echo -e "$mounts" | sed -n $line_num'p') partition has $((100-$(echo -e "$free_space" | sed -n $line_num'p')))% free space"
+			sudo echo "Spaced: $LC_i: $(echo -e "$mounts" | sed -n $line_num'p') partition has less than 2% free space!"
+			echo -e "$(df -lh | head -n1)\n$df_line" | mail -s "space.d: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$LC_mailto"
+			"$LC_shuttle_path"/shuttle -p -n all "$LC_i: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$(echo -e "$mounts" | sed -n $line_num'p') partition has $((100-$(echo -e "$free_space" | sed -n $line_num'p')))% free space"
 		fi
 	done
 EOF
diff --git a/sysmon b/sysmon
--- a/sysmon
+++ b/sysmon
@@ -1,37 +1,34 @@
 #! /bin/bash
 
-# Sysmon - Check CPU/GPU temps and system load
+# Sysmon - Check CPU/GPU temps and system load 
 # 	By Andy Forceno <andy@aurorabox.tech>
 #
 # INFO: This script depends on sensors and nvclock
 
-# If any hosts have an Nvidia card, set this to yes
-# You must add all hostnames to conditional on line 29
-# like so: if [[ "$LC_i" = "Host 1" || "Host 2" || "Host 3" ]], then
-nvcard="yes"
+# If any hosts have an Nvidia card, set nvcard=yes in $conf_path/shuttle-utils.conf
+# You must add all hostnames to conditional on line 29 like so: 
+# if [[ "$LC_i" = "Host 1" || "Host 2" || "Host 3" ]], the
 
-# Send push notif when CPU/GPU goes above this value
-temp_thresh="90"
-
-# Send push notif when load (1 min average) goes above this value
-load_thresh="5"
-
-# Location of local disk copy of repo
-BASEDIR="/home/andy/scripts/bin"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if machines are available before updating
-source "$BASEDIR"/hosts_check
+source "$bin_path"/hosts_check
 
 for i in "${HOSTS[@]}"; do
 # Pass local vars to remote hosts
-	ssh "$i" LC_0="$0" LC_i="$i" LC_nvcard="$nvcard" LC_percent="$percent" LC_temp_thresh="$temp_thresh" LC_load_thresh="$load_thresh" bash << 'EOF' 
+	ssh "$i" LC_i="$i" LC_nvcard="$nvcard" LC_percent="$percent" LC_temp_thresh="$temp_thresh" LC_load_thresh="$load_thresh" LC_shuttle_path="$shuttle_path" bash << 'EOF' 
 	if [[ "$LC_nvcard" = "yes" ]]; then
 		if [[ "$LC_i" = "Aurorabox" ]]; then 		# INFO: Add all hosts with Nvidia cards here
 			temp=$(sudo nvclock -T | tail -n1 | awk '{ print $4 }' | sed 's/C//g')
-			# echo -e "$LC_0: $LC_i: GPU temperature: \t $(echo "$temp" | sed 's/$/°C/g')"
+			# echo -e "sysmon: $LC_i: GPU temperature: \t $(echo "$temp" | sed 's/$/°C/g')"
 		else
 			temp=$(sensors -u | awk -F: '/temp1_input/ { print $2 }' | head -n1 | sed 's/\..*$//g')
-			# echo -e "$LC_0: $LC_i: CPU temperature: \t $(echo "$temp" | sed 's/$/°C/g')"
+			# echo -e "sysmon: $LC_i: CPU temperature: \t $(echo "$temp" | sed 's/$/°C/g')"
 		fi
 	fi
 
@@ -40,11 +37,11 @@ for i in "${HOSTS[@]}"; do
 
 # Evaluate temps, send push if > threshold
 	if (( "$temp" >= "$LC_temp_thresh" )); then
-		/usr/bin/shuttle -p -n all "$LC_i: Temperatures above $(echo "$LC_temp_thresh" | sed 's/\..*$/°C/g') detected!" "Current temperature: $LC_temp at $(date +%H:%M) on $(date +%Y-%m-%d)"
+		"$shuttle_path"/shuttle -p -n all "$LC_i: Temperatures above $(echo "$LC_temp_thresh" | sed 's/\..*$/°C/g') detected!" "Current temperature: $LC_temp at $(date +%H:%M) on $(date +%Y-%m-%d)"
 	fi
 
 	if (( "$load_int" > "$LC_load_thresh" )); then
-		shuttle -p -n all "$LC_i: System load above $(echo "$LC_load_thresh") detected!" "Current load: $load_raw at $(date +%H:%M) on $(date +%Y-%m-%d)"
+		"$LC_shuttle_path"/shuttle -p -n all "$LC_i: System load above $(echo "$LC_load_thresh") detected!" "Current load: $load_raw at $(date +%H:%M) on $(date +%Y-%m-%d)"
 	fi
 EOF
 done
diff --git a/update_all b/update_all
--- a/update_all
+++ b/update_all
@@ -5,58 +5,59 @@
 #
 # INFO: This script requires Dsh, Distributed Shell
 
-# Location of local disk copy of repo
-BASEDIR="/home/andy/scripts/bin"
+if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
+	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
+else
+	echo "SHuttle-utils: Error: No config file found!"
+	exit 1
+fi
 
 # Check if machines are available before updating
-source "$BASEDIR"/hosts_check
+ source "$bin_path"/hosts_check
 
 # Output online hosts to DSH hosts group file
 printf '%s\n' "${HOSTS[@]}" > /etc/dsh/group/up
 
 # Full path to dpkg.log (user must have read permission)
-logfile="/var/log/dpkg.log"
+dpkg_log="/var/log/dpkg.log"
 
-# TODO: See if it will send dpkg update files from here
-config_path="~/.config/shuttle-utils"
-
-# Device to send package update push notifications to 
-device="all"
-
-# Set non-interactive frontend to avoid display issues with config file choice frontend
-export DEBIAN_FRONTEND="noninteractive"
 # Connect to each remote host specified in the /etc/dsh/group/up file and run apt-get update, upgrade, and autoremove
-dsh -v -g up sudo apt-get -qq update 
+dsh -vM -g up -c sudo apt-get -qq update 
+# Set non-interactive frontend to avoid display issues with config file choice frontend
 # Choose to preserve current config files on system, rather than package maintainer defaults 
-dsh -v -g up sudo apt-get -qq -o Dpkg::Options::="--force-confold" --force-yes -y upgrade
-dsh -v -g up sudo apt-get -qq --force-yes -y autoremove
+dsh -vM -g up -c DEBIAN_FRONTEND="noninteractive"
+dsh -vM -g up -c sudo apt-get -qq -o Dpkg::Options::="--force-confold" --force-yes upgrade
+dsh -vM -g up -c sudo apt-get -qq --force-yes autoremove && wait $!
 
 for i in "${HOSTS[@]}"; do
-	ssh "$i" LC_i="$i" LC_device="$device" LC_logfile="$logfile" bash << 'EOF'
+	ssh "$i" LC_i="$i" LC_device="$device" LC_dpkg_log="$dpkg_log" LC_conf_path="$conf_path" LC_shuttle_path="$shuttle_path" bash << 'EOF'
 	curr_date=$(date +%Y-%m-%d)
-	upgraded=$(awk '/upgrade/ && /'$curr_date'/ { print $1 "   " $4 }' "$LC_logfile" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
+	upgraded=$(awk '/upgrade/ && /'$curr_date'/ { print $1 "   " $4 }' "$LC_dpkg_log" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
 	# TODO: Some upgraded packages are matched here, not entirely sure why (they aren't listed in removed, so they aren't being removed and then re-installed)
-	installed=$(awk '/installed/ && /'$curr_date'/ { print $1 "   " $5 }' "$LC_logfile" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
-	removed=$(awk '/remove/ && /'$curr_date'/ { print $1 "   " $4 }' "$LC_logfile" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
+	installed=$(awk '/installed/ && /'$curr_date'/ { print $1 "   " $5 }' "$LC_dpkg_log" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
+	removed=$(awk '/remove/ && /'$curr_date'/ { print $1 "   " $4 }' "$LC_dpkg_log" | sed -e 's/\:i386//g' -e 's/\:amd64//g' -e 's/\:all//g' -e 's/\:armhf//g' | sort | uniq)
 	
+	if [ ! -d "$LC_conf_path" ]; then
+		mkdir "$LC_conf_path"
+	fi
+	if [ ! -f "$LC_conf_path"/dpk-$curr_date ]; then
+		touch "$LC_conf_path"/dpkg-$curr_date
+	fi
 	# Export the recently installed packages to a file, and push that. File must be in cwd, otherwise Pushbullet doesn't push it (a bug in SHuttle, most likely)
 	# TODO: I was unsuccessful in getting Pushbullet API to send the raw data, presumably because of the way JSON handles multi-line text
-	echo -e "$LC_i:\nInstalled:\n------\n$installed\nUpgraded:\n------\n$upgraded\nRemoved:\n------\n$removed" | column > dpkg-$curr_date
-	# This is family member's PC, so pushes sent from it should go to my Pushbullet account, not their's 
-	if [[ -n "$upgraded" || -n "$installed" || -n "$removed" ]]; then
-		if [[ "$LC_i" = "Vivobook" ]]; then
-			LC_device="t4exanadu@gmail.com"	
+	echo -e "Package updates and removals on $LC_i\n\nInstalled:\n$installed\n\nUpgraded:\n$upgraded\n\nRemoved:\n$removed" > "$LC_conf_path"/dpkg-$curr_date
+
 		fi
-		/usr/bin/shuttle -p -f "$LC_device" "$LC_i: Package updates for $curr_date" "" "dpkg-$curr_date" 
-		rm -f dpkg-$curr_date
+		"$LC_shuttle_path"/shuttle -p -f "$LC_device" "$LC_i: Package updates for $curr_date" "" "$LC_conf_path/dpkg-$curr_date" 
+		rm -f "$LC_conf_path"/dpkg-$curr_date
 	# Pushbullet API won't send this. If you get it working, let me know or make a commit! :-)
+	# It probably requires some changes to shuttle
 		# shuttle -p -n "$LC_device" "$LC_i: Package updates for $curr_date" "$(echo -e "Installed:\n------\n$installed\nUpgraded:\n------\n$upgraded\nRemoved:\n------\n$removed" | column)"
 
 	# Aonther attempt. This sends everything, but newlines are removed
 		# shuttle -p -n "$LC_device" "$LC_i: Package updates for $curr_date" "$(printf '%s\n' $(<dpkg-$curr_date))"  
 
-	# Mailing of LAN hosts is broken on most of my Linux boxes, so this is not fully tested
-	# it should work fine, though!
+	# Mailing of LAN hosts is broken on most of my Linux boxes, so this is disabled for now
 		# echo -e "Installed:\n------\n$installed\nUpgraded:\n------\n$upgraded\nRemoved:\n------\n$removed" | column | mail -s "Updated packages for $curr_date" root@"$HOSTNAME"
 		fi
 EOF
